dist: xenial
language: csharp
mono: none
sudo: required

git:
    depth: 3
    quiet: true

addons:
    snaps:
      - name: dotnet-sdk
        confinement: classic
        channel: 3.1/stable

install:
    - export PATH="$PATH:/home/travis/.dotnet/tools"
    - export PATH="$PATH:$HOME/.local/bin"
    - sudo snap alias dotnet-sdk.dotnet dotnet

global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=1

solution: FreeserfNet.sln
script:
  - dotnet --version
  - dotnet restore FreeserfNet.sln
  - dotnet msbuild /p:Configuration=LinuxRelease FreeserfNet.sln
  - dotnet publish -c LinuxRelease FreeserfNet/FreeserfNet.csproj /p:PublishSingleFile=true -r ubuntu-x64

stages:
  - name: deploy
    if: branch = master AND type = push AND os = linux

before_deploy:
  - mkdir deploy
  - cd deploy
  - mkdir FreeserfNet
  - cd ..
  - cp -r FreeserfNet/bin/LinuxRelease/ubuntu-x64/publish/. deploy/FreeserfNet/
  - cp -r FreeserfNet/assets deploy/FreeserfNet/assets
  - cp changelog.txt deploy/FreeserfNet/changelog
  - cd deploy/FreeserfNet
  - chmod +x FreeserfNet
  - cd ..
  - tar -czf ../Freeserf.net-Linux.tar.gz FreeserfNet

deploy:
    provider: releases
    api_key:
      secure: ZFMzgJw5vKrmPOcOL/6SCMzo0GgT40n9aG0iDDIfcEeyZYGKQ347mPZnNMaHt6Q0ZBmOF6xW57+qhOA8nQxklj+68EhBL/kkptZAiyk8RAJ6BBqLPzGcSGZeBeEZ7G/A1bf8MMCMLyphI1y1VfaqM4Rj16TrZthGqBfhGivlERZoicn5u9ITLiOoooYO+xCMmO7v4RhP7H1t1taHHvfBxfqh/Heq/QcGaW9tfT9xxFK5maNruifL2U58alCnnANFub2B1FUhV+VeboQzFKvdzbd1lW/FuowSIfxNZhQYdfyqD9Vmb6JHXeVSexcCTjyMg2hiKKkbbY0WJb8nKPn1OyqO0+bJNaEBqiGHCVnmHxTct6wtBGkfW5W6g09qTCoeOMw+VIvU2WDkfvflFYtkX3wyzM4TvHcZu2on3ooG15fbUOf0Q8nGFLp7Tfj3SqAxgqbqHw7AkQdiNEkyqvrZk22plV+2vLMtQcXeIFGDxfX9Y21cheenU2mHfCr9IdesYQzIXUy/OLK5/ey0LQgLhv/BMpPJkmgu2XbgAfBLt8K3cTf3T3VS/9q0VPoNOSshn0Goc77F5C0nWGIrwF2/MW4fiHjZ6tOaXlIWwHBsOUJHGzdUSwCJyIxd/iiivFha/WoeyRbh5VGjdFlrhmT6QEEzBRAfLUR+CaKpjdRKBc8=
    file: Freeserf.net-Linux.tar.gz
    skip_cleanup: true
    draft: true
    overwrite: true
    prerelease: false
    name: $TRAVIS_TAG
    body: 'Release $TRAVIS_TAG'
    on:
        tags: true
